### PR TITLE
Enable nonblocking operation

### PR DESCRIPTION
**Pull request by andreasley**
This PR is part of a series to enable nonblocking operation in Vapor and solve https://github.com/vapor/engine/issues/66

This PR depends on https://github.com/vapor/engine/pull/71

### CODE REVIEW

**Comment by tannernelson** [comment]
What was the reasoning behind changing `boot` -> `start`? If we keep that we will have to add some extensions to maintain compatibility with 1.x.

**Comment by andreasley** [comment]
Sorry for not explaining that. I thought it made sense to be able to start and stop servers directly without using `run()` (for example when using Vapor as an embedded webserver). This provides some flexibility, especially if there's already a `RunLoop`. That's why I used the word "start". The original, blocking `bootServers` functions are still there, but aren't called anymore. Since they weren't public, API compatibility shouldn't be an issue, or am I missing something?

**Comment by andreasley** [comment]
Here's a PR for improved cleanup after stopping or releasing a `Server`: https://github.com/vapor/engine/pull/78

**Comment by tannernelson** [comment]
I must have missed something when reading. It all looks good. :) 👍

**Pull request merged**
