### PR TITLE
add skelpo to compat suite

### PR DESCRIPTION
**Pull request by tanner0101**
https://forums.swift.org/t/vapor-compatibility-test-suite/20500/2

### CODE REVIEW

**Comment by tanner0101** [comment]
@calebkleveter any advice on how to fix this:
```
/root/PayPal/.build/checkouts/Cgd.git-140912051763875496/module.modulemap:2:9: error: header '/usr/include/gd.h' not found
        header "/usr/include/gd.h"
               ^
/root/PayPal/.build/checkouts/SwiftGD.git--7412823828897963172/Sources/Format.swift:3:12: error: could not build C module 'Cgdlinux'
    import Cgdlinux
           ^
/root/PayPal/.build/checkouts/Cgd.git-140912051763875496/module.modulemap:2:9: error: header '/usr/include/gd.h' not found
        header "/usr/include/gd.h"
               ^
/root/PayPal/.build/checkouts/SwiftGD.git--7412823828897963172/Sources/Format.swift:3:12: error: could not build C module 'Cgdlinux'
    import Cgdlinux
           ^
/root/PayPal/.build/checkouts/Cgd.git-140912051763875496/module.modulemap:2:9: error: header '/usr/include/gd.h' not found
        header "/usr/include/gd.h"
               ^
/root/PayPal/.build/checkouts/SwiftGD.git--7412823828897963172/Sources/Format.swift:3:12: error: could not build C module 'Cgdlinux'
    import Cgdlinux
           ^
/root/PayPal/.build/checkouts/Cgd.git-140912051763875496/module.modulemap:2:9: error: header '/usr/include/gd.h' not found
        header "/usr/include/gd.h"
               ^
/root/PayPal/.build/checkouts/SwiftGD.git--7412823828897963172/Sources/Format.swift:3:12: error: could not build C module 'Cgdlinux'
    import Cgdlinux
           ^
/root/PayPal/.build/checkouts/Cgd.git-140912051763875496/module.modulemap:2:9: error: header '/usr/include/gd.h' not found
        header "/usr/include/gd.h"
               ^
/root/PayPal/.build/checkouts/SwiftGD.git--7412823828897963172/Sources/Format.swift:3:12: error: could not build C module 'Cgdlinux'
    import Cgdlinux
           ^
```

**Comment by calebkleveter** [comment]
@tanner0101 Try installing `apt-get libgd-dev` on Linux (`gd` with Homebrew on macOS).

And few notes about testing some of the Skelpo/SwiftCommerce servicea:

- Only the `ModelTests` module in PayPal contains 100% succeeding test at the moment.
- OrderSystem and ProductManager both have postman collections that can be tested using something like [Newman](https://learning.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman/)
- OrderSystem relies on ProductManager to get and verify data, so unless ProductManager is running at the same time, things will start exploding.

If I can help get anything else sorted out, let me know!

**Comment by tanner0101** [comment]
@calebkleveter could you take a look at this error output and let me know if you have any ideas on what could fix it?

https://circleci.com/gh/vapor/vapor/5141

**Comment by calebkleveter** [comment]
@tanner0101 I just made some changes to the PayPal package tests and updated the git hash in the compat test suite. I don't have a Linux VM setup locally, so we'll wait for the CI to see if that fixed it.

**Comment by calebkleveter** [comment]
Noop. That didn't work. Somehow we need to get tests in different modules to run properly on Linux, and I don't know how to do that. I can try to get this sorted out when I have time, but I don't know when that will be.

**Comment by tanner0101** [comment]
@calebkleveter ok sounds good, i'll just remove this from the workflow for now. We can add back later.

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 1067 coins.

**Pull request merged**
