### PR TITLE
Middleware for CORS support [WIP]

### PR DESCRIPTION
**Pull request by nickskull**
This is the first draft of the middleware for proper CORS support in responses. 

It's still WIP as there are tests missing and there might be some slight changes, but I'd love some feedback from anyone who has more experience with handling CORS.

I've tried to follow the diagram [located here](https://www.html5rocks.com/static/images/cors_server_flowchart.png) as closely as possible. 

If there is no feedback I will finish tests and verify that it works on Linux and it should be ready for merging! 🎉 

## What is it?

CORS is a standard mechanism that can be used by all browsers for implementing cross-domain requests. The spec defines a set of headers that allow the browser and server to communicate about which requests are (and are not) allowed. CORS continues the spirit of the open web by bringing API access to all.  

[http://enable-cors.org/](http://enable-cors.org/)

## Impact on existing code  

None as this is a purely additive feature.

### CODE REVIEW

**Comment by Casperhr** [comment]
Awesome to get this into a web framework. It's always a pain in the *** :)

**Comment by LoganWright** [comment]
@nickskull awesome, I merged you out unfortunately though, would you mind updating your branch manually?

We can also bring the branch over to this repo to get it in.

**Comment by nickskull** [comment]
@LoganWright Yeah, I will update the branch and finish the tests this week, it can get merged in :)

**Comment by LoganWright** [comment]
Closing for #753 so that I could merge 👍

**Pull request closed without merging**
