### PR TITLE
Prevent vapor from crashing during a crash in third-party code, obfuscating the real problem

### PR DESCRIPTION
**Pull request by Joannis**
If a third-party library or user defined code crashed a Vapor app, the Vapor Application deinit will crash the app before the real issue pops up. This leads to frustrating debug sessions

### CODE REVIEW

**Review by gwynne — APPROVED** [review]
Yeah, I gotta come down in favor of this, ultimately. The importance of calling out the misbehavior is not enough to justify the massive penalties to debugging and usability that people have been dealing with.

**Comment by 0xTim** [comment]
@Joannis ready for this to be merged?

**Comment by 0xTim** [comment]
I'm wondering if we should add a test for this

**Comment by Joannis** [comment]
I'll add a test, because the simple condition is "the test doesn't crash"

**Comment by Joannis** [comment]
> They should be fixed by #2897 

Let's merge after tests succeed then

**Pull request merged**
