### PR TITLE
Fix crash in DotEnv parser

### PR DESCRIPTION
**Pull request by antoinepalazzolo**
Previously, when .env file with a comment as the last line was parsed, an infinite recursive loop crashed the application.
The comment is now properly skipped.

### CODE REVIEW

**Comment by 0xTim** [comment]
@antoinepalazzolo could you update the code so it can be merged?

**Review by 0xTim — APPROVED** [review]
LGTM

**Comment by 0xTim** [comment]
Additionally if you could update the description of the PR - that will become the release notes for the release. Thanks!

**Comment by tanner0101** [comment]
These changes are now available in [4.36.2](https://github.com/vapor/vapor/releases/tag/4.36.2)

**Pull request merged**
