### PR TITLE
Correctly handle invalid numbers in range validations

### PR DESCRIPTION
**Pull request by fred-sch**
Previously trying to perform a range validation check on `Float.nan` would cause a `fatalError` - this correctly handles it and throws an error instead.

Closes https://github.com/vapor/vapor/issues/2965.

### CODE REVIEW

**Comment by fred-sch** [comment]
I think there is unfortunately no real way to avoid the api breakage. Admittedly, it is kind of counterintuitive that there should be a `case notComparable` for something that operates on the `Comparable` protocol, but `FloatingPoint.nan` is exactly this case as it will always yield `false` in any comparison (even comparing it with itself).

**Comment by 0xTim** [comment]
Just skimming this - since the initialiser is internal we could mark it as throwing and throw an error if you try to compare something that isn't comparable and then handle that up the stack. Just a thought and not sure if higher up in the stack can handle it easily. What do you think?

**Comment by fred-sch** [comment]
That is a good idea! I did as you asked in https://github.com/vapor/vapor/pull/2966/commits/f87494b25bd7955beca7d9d61e2ea804c7fac668

**Review by 0xTim — APPROVED** [review]
Thanks!

**Pull request merged**
