### PR TITLE
Remove unnecessary check

### PR DESCRIPTION
**Pull request by siemensikkema**

### CODE REVIEW

**Comment by vzsg** [comment]
I think that check was intentional - the server wouldn't print detailed error messages in production, just like one would disable PHP notes and warnings.

But it would be nice if it didn't depend on the "production" environment, but was a separate configuration option.

**Comment by siemensikkema** [comment]
@vzsg isn't that covered by the guard statement above it though?

**Comment by vzsg** [comment]
My bad. You're completely right, I only read the change set 😞 .

**Comment by siemensikkema** [comment]
no worries! I should've added a line of explanation :)

**Comment by tanner0101** [comment]
thanks :)

**Pull request merged**
