### PR TITLE
Add date support

### PR DESCRIPTION
**Pull request by cwoloszynski**
I am submitting a series of pull requests to add Date as a class in Node and datetime and timestamp support in Fluent. This allows for full support for time throughout Vapor.

Specifically, there are pull requests for Vapor, Fluent, Node, JSON, MySQL, Leaf, and FluentMySQL

### CODE REVIEW

**Comment by LoganWright** [comment]
@cwoloszynski there's a lot of code here across a lot of repos and we're trying to go through em all to get a picture of what this means for our public api, versioning requirements, and internal intentions. Just wanted to let you know that we're working on it.

Are you by chance in our [slack](http://vapor.team), and if so, would you ping us so we can match the name and get some chat there about these changes.

Thanks again for participating in Vapor!

**Comment by cwoloszynski** [comment]
Thanks for getting back to me.  I am @charlie-wolo on your slack!

Charlie

**Comment by cwoloszynski** [comment]
Oh, and by the way, sorry for the sprawling changes. I could not see how to do it otherwise.

**Comment by LoganWright** [comment]
Moving this conversation to slack in the beginning of Vapor 2.0 api discussions, thanks so much for the head start on this @cwoloszynski the work is definitely appreciated and won't be lost!

**Pull request closed without merging**
