### PR TITLE
Routing type validation

### PR DESCRIPTION
**Pull request by tanner0101**
Converts `RoutingError` to `404 Not Found`

### CODE REVIEW

**Comment by waghanza** [comment]
awesome :tada:

Does this mean that 2 routes could be configured depending on `type` ?

I mean could we have **both**

```swift```
router.get("users", Int.parameter) { (req) throws -> Int
```
and
```swift
router.get("users", String.parameter) { (req) throws -> String
```

**Comment by tanner0101** [comment]
@waghanza no, unfortunately not. I think it would be _possible_ to do this, but the current implementation will only respect the last registered route. So if you do, for example:

```swift
router.get("users", String.parameter) { ... }
router.get("users", Int.parameter) { ... }
```
then
```
GET /users/foo
```
will result in a 400 error because foo does not match `Int`.

**Comment by waghanza** [comment]
@tanner0101 adding such a feature will be awesome

Several frameworks allow to define route according to pattern matching, it think this is a very valuable

**Comment by 0xTim** [comment]
@tanner0101 I was under the impression (that in Vapor 3 at least) it would try all registered routes in the order they were registered, so if `Int.parameter` was before `String.parameter` it would work (could be completely wrong!) - obviously `String.parameter` would intercept the `Int.parameter` if they were registered the other way. 

As for the 404 - should it be 404 or 400? I wonder what's semantically correct here

**Comment by waghanza** [comment]
@OxTim `400` `404` `422` are the only options I have seen in the list https://github.com/the-benchmarker/web-frameworks

And for me, using an other http status is not **correct** according to http standard

**Pull request closed without merging**
