### PR TITLE
Extract multipart encoding/decoding from Vapor into MultipartKit

### PR DESCRIPTION
**Pull request by JaapWijnen**
Extract previously embedded multipart encoding and decoding functionality into a standalone package, MultipartKit (#2553).

The public API of MultipartKit is exported so there is no need to import MultipartKit if you already import Vapor.

See: https://github.com/vapor/multipart-kit

### CODE REVIEW

**Comment by siemensikkema** [comment]
@JaapWijnen could you update this with the new MultipartKit tag?

**Comment by siemensikkema** [comment]
Suggested title: Extract multipart encoding/decoding from Vapor into MultipartKit
Suggested body:

> Extract previously embedded multipart encoding and decoding functionality into a standalone package, MultipartKit (#2553).
>
> The public API of MultipartKit is exported so there is no need to import MultipartKit if you already import Vapor.
>
> See: https://github.com/vapor/multipart-kit

**Comment by JaapWijnen** [comment]
@siemensikkema updated the title as well, somehow that didn't persist, probably forgot to save ;) All ready for merging! :)

**Review by siemensikkema — APPROVED** [review]
LGTM!

**Pull request merged**
