### PR TITLE
Add support for Codable types with URL properties to URLEncodedFormData.

### PR DESCRIPTION
**Pull request by EmperiorEric**
Add support for encoding and decode URLs. Fixes https://github.com/vapor/url-encoded-form/issues/24 now that its been moved here for Vapor 4.

### CODE REVIEW

**Comment by tanner0101** [comment]
Thanks @EmperiorEric. This may conflict with https://github.com/vapor/vapor/pull/2180 so I'm going to hold off merging for now until we get that larger PR through. It should be much easier to fix any conflicts here.

**Comment by EmperiorEric** [comment]
Sounds good 👍 Just ping me when its through and I can clean up any conflicts.

**Comment by tanner0101** [comment]
@EmperiorEric the PR has been merged into master now. The protocol was renamed to `URLQueryFragmentConvertible`. 👍

**Comment by tanner0101** [comment]
This has been fixed on master, thanks!

**Pull request closed without merging**
