### PR TITLE
nio-based websockets

### PR DESCRIPTION
**Pull request by tanner0101**
- [x] adds NIO-based WebSocket support to Vapor
- [ ] add fix-it and deprecations to old websocket API

Due to the way NIO handles HTTP protocol upgrades, the API for WebSockets will need to change quite a bit. 

The updated API allows you to register a `WebSocketServer` like you would any other service (in your `configure.swift` file).

```swift
let websockets = EngineWebSocketServer.default { ws, req in
    ws.onText { text in
        ws.send(text.reversed())
    }
}
services.register(websockets, as: WebSocketServer.self)
```

By default, all websocket upgrade requests will be accepted, and the connected websocket will be supplied to the closure.

It's also possible to specify another closure that can accept or deny a websocket connection given the HTTP request that requested it.

With this new design, websocket requests and responses will no longer flow through the application middleware structure. This is an important difference to the previous structure and to the structure from Vapor 2. Re-creating that would require opting out of the NIO defaults for websocket and creating a custom HTTP upgrader implementation. I don't think that's worth it to keep the old API, especially when this will be the case for future HTTP protocol upgrade handlers as well. However, this is open to discussion.

### CODE REVIEW

**Comment by pedantix** [comment]
@tanner0101 this looks good to me. 

For purposes of theory only, my current application does not have this problem:

1. How do we "mount" an EngineWebSocketServer. request. How do we distinguish websocket server requests "/anonymous_socket" and "/user_socket", I realize these are contrived examples, however sometimes it is convienent to have more then one mount point.

**Comment by tanner0101** [comment]
@pedantix the second parameter to the `onUpgrade` closure is the Request the initialized this WebSocket connection. That request contains the URI, so you could do something like:

```swift
let websockets = EngineWebSocketServer.default { ws, req in
    if req.uri.path == "/anonymous_socket" { ... } else { ... }
    ws.onText { text in
        ws.send(text.reversed())
    }
}
services.register(websockets, as: WebSocketServer.self)
```

The optional `shouldUpgrade` closure is also supplied the `Request` that is requesting upgrade to WebSocket protocol. This would allow you to dynamically accept/decline upgrade requests using the URI path as well.

**Comment by twof** [comment]
Are there any plans for some sort of routing API? Manually checking the path is doable, but pretty clumsy and a significant loss in usability from pre-NIO

**Comment by tanner0101** [comment]
@twof yes it would be possible to build back that API on top of this method, but I wonder how much it was being used. The reason we had that API previously was simply because that's how the implementation worked behind the scenes. WebSocket routes were just another route. Now upgrading to a WebSocket is a step that happens before the HTTP request ever enters your application. I think there should be a convincing reason to add back in the router-like behavior since it would now require additional code to achieve it.

**Comment by twof** [comment]
For inspiration here are how libraries in some other languages facilitate websockets:

[Kotlin + SpringBoot](https://medium.com/@codemwnci/kotlin-springboot-and-websockets-276029b22482): Looks pretty manual. You write a class that inherits from `TextWebSocketHandler` and then register that class to a route

```kotlin
registry.addHandler(ChatHandler(), "/chat").withSockJS()
```

[node.js + ws](https://github.com/websockets/ws): Instantiate a WebSocket object with a path, and then set action callbacks afterwards. They also seem to indicate a difference between a websocket server/client and a websocket server, but I'm not sure what it is.

```javascript
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });

  ws.send('something');
});
```

[Python + Flask-SocketIO](https://flask-socketio.readthedocs.io/en/latest/): This one has the most features of any of the libraries here, including some I'd like to see in Vapor. When setting up a socket action callback, you can indicate a "namespace" which is very similar to Vapor's routes as far as I can tell

```python
@socketio.on('my event', namespace='/test')
def handle_my_custom_namespace_event(json):
    print('received json: ' + str(json))
```

Features I'd like to see in Vapor's WebSockets:
1. Maintain a collection of currently open connections per route. It should be easy to see who is connected to your route. I'm currently doing this by appending each new `WebSocket` to an array, but I'm sure this isn't thread safe or anything, so if it was handled by Vapor instead, that would be ideal.

```swift
var pingSessions: [WebSocket] = []

router.websocket("ping") { (req, ws) in
    pingSessions.append(ws)
    
    ws.onClose({ (ws, data) in
        pingSessions.removeIf { $0 === ws }
        print(pingSessions)
    })
}
```
2. Support broadcasting. I didn't realize `.send(string:)` didn't send to every connection to my WS route until I started doing this research. This shouldn't be too difficult once the above is supported. I'm currently broadcasting via an extension on `WebSocket`.

```swift
extension WebSocket {
    static func broadcast(msg: String, to all: [WebSocket]) {
        all.forEach { $0.send(string: msg) }
    }
    
    static func broadcast(future: Future<String>, to all: [WebSocket]) {
        all.forEach { $0.send(future: future) }
    }
}
```

3. I could be wrong, but I don't think there's any need to be passing a `WebSocket` through to `.onString()`, etc. 

```swift
router.websocket("ping") { (req, ws1) in
    ws1.onClose({ (ws2, data) in
        pingSessions.removeIf { $0 === ws }
        print(pingSessions)
    })
}
```

AFAIK, `ws1`, and `ws2` will always point to the same instance of `WebSocket`

That's all I've got for now, but perhaps someone with more experience with WebSockets has some other ideas

**Comment by tanner0101** [comment]
After some discussion in slack:

We think websockets should support a limited, separate form of routing. Specifically:
- GET only
- no body
- no middleware
- route parameters
- route groups (for building path components)

```swift
let websockets = EngineWebSocketServer.default()

websockets.get("users", User.parameter) { ws, req in
    let user = try req.parameter(User.self)
    ws.onText { text in
        ws.send(text.reversed())
    }
}
services.register(websockets, as: WebSocketServer.self)
```

**Comment by pedantix** [comment]
I would like to point out one other Nitpick. The spec for WS presently stipulates that basic auth is part of the spec. However a lot of clients don't end up including this in the headers, however I think they all end up supporting cookies, we may want to specify that, or are we going to let Nio completely dictate that layer of the exchange?

**Comment by vzsg** [comment]
(Just a nitpicking of Twof's comment: socket.io is a framework that works with many languages; and not just above websockets, but with long polling too. It's not really comparable to the low-level WS clients listed.)

**Comment by tanner0101** [comment]
@pedantix you get access to the incoming headers on both `shouldUpgrade` and `onUpgrade`. It's also possible to set the response headers to be sent back in the switch protocols response, which should allow you to set cookies.

**Comment by pedantix** [comment]
For what it is worth I support this plan. Routable Sockets with access to headers and cookies and further can send and receive big messages! Count me in. @twof I have had some dealings with Spring STOMP sockets, and SockJS, as far as doing that sort of thing this will provide the essential primary building block.

**Pull request merged**
