### PR TITLE
Fix for decoding percent escaped query keys (#2383)

### LINKED ISSUE #2383: URLQueryContainer doesn't decode escaped []
Possibly related to https://github.com/vapor/vapor/issues/1055

### Steps to reproduce

Send a request using `Foundation` to something similar to:
```
GET /users?page[offset]=0&page[limit]=50&filter[ids]=auth0|abc123
```
Foundation will percent escape the url to something like this:
```
GET /users?page%5Boffset%5D=0&page%5Blimit%5D=50&filter%5Bids%5D=auth0%7Cabc123
```

Try to decode the query:
```
try request.query.get([String: String].self, at: "filter")
```

### Expected behavior

```
{ ids: "auth0|abc123" }
```

### Actual behaviour

```
nil
```

### Environment

* Vapor Framework version: 4.8
* OS version: macOS 10.15.5

### PR DESCRIPTION
**Pull request by dlbuckley**
This change fixes #2383 and brings consistency to how query array values are accessed.

Previously getting an array from the URL query you would have to include `[]` in the key. This is not needed for any other value access, and with this change is no longer needed to access arrays. This means the query string:

`emailsToSearch%5B%5D=xyz`

Used to be accessed by calling:

`request.query.get([String].self, at: "emailsToSearch[]")`

Now it can be accessed by calling:

`request.query.get([String].self, at: "emailsToSearch")`

### CODE REVIEW

**Comment by dlbuckley** [comment]
@tanner0101 do you have any comments you would like to add to this?

**Comment by Joannis** [comment]
@MrLotU you didn't end up merging this yet. Do you need to change something like the release notes? If so, can you guide this to completion?

**Comment by MrLotU** [comment]
@Joannis I was actually waiting for @tanner0101 to shed some light on this too, since he tackled the other arrays in query PR IIRC :)

**Comment by dlbuckley** [comment]
@tanner0101 is there any chance this will get merged or shall I close it? Is there a process that I'm missing for external contributions to Vapor?

**Comment by Joannis** [comment]
@dlbuckley I'm not sure why he's not responded yet. As you might imagine, he's got a lot of issues and PRs to attend to on a daily basis. Aside from his own software development, that is. So it's very possible that this PR slipped his mind, or has been on a backlog of time kind.

**Comment by dlbuckley** [comment]
@Joannis thanks for the reply. I totally understand that time constraints can lead to PR's getting lost/forgotten about. But I must say is a bit discouraging to have a PR open for so long without any indication if it's ever going to get merged. Is this bottleneck something that is being looked into, or just a known problem that there is no solution for yet?

**Comment by tanner0101** [comment]
Hey @dlbuckley, thanks for the PR! Sorry for the long review period. I'm working through my backlog slowly but surely. 

Query string parsing has been a source of issues since Vapor 1 and I wanted to do a bit of research here first before responding. I've posted my findings here: https://github.com/vapor/vapor/issues/2383#issuecomment-656864600

In short, it seems that percent decoding keys (even though it seems wrong to me) is what most frameworks do. I always viewed this as a bug in Vapor 3's implementation but it seems like it was actually a feature haha.

I'm merging this PR into a local branch where I can add some more tests and make sure Vapor is behaving similarly to other frameworks.

**Pull request merged**
