### PR TITLE
Logout wrapper function

### PR DESCRIPTION
**Pull request by adriencanterot**
Hello everyone,
Regarding the auth module
### Introduction
This PR aims at adding a logout wrapper function around 
```swift
subject().logout()
```

### Motivation
Currently, ` request.subject()` is internal and is wrapped with an auth helper that currently allows logging in an user and accessing it through `request.auth.login(_)` and `request.user()` however there is no way for logging the user out.

### Proposed solution
cf Intro.

### Code snippet
Logging out the user would look like 
```swift 
request.auth.logout()
```

### Impact
None.

### Alternative considered
The `request.subject()` method could be made public but but there wouldn't be any more use for an Auth helper.

### Tests
This PR should be delayed since I didn't see any available test for the auth helper. I didn't write any for this PR, however, I'd be happy to add some if interested in another one.

### CODE REVIEW

**Comment by tannernelson** [comment]
This looks good to me. Could you add a test for it?

**Comment by adriencanterot** [comment]
Hi, I added a few tests for Login/out functions in Vapor, I made a few changes across VaporTests so you might want to review it :)

**Comment by tannernelson** [comment]
Very nice. :)

**Comment by edjiang** [comment]
This functionality is definitely needed! Was gonna log an issue but looks like you've already taken care of it @adriencanterot! =]

**Pull request merged**
