### PR TITLE
Update package to set minimum deployment target

### PR DESCRIPTION
**Pull request by twof**
Currently if you try to add Vapor 4 to an iOS project, it complains that some of the APIs used aren't available until iOS 10, so you need to add flags to check the current iOS version. This is resolved in this PR by setting the minimum iOS version to 11. I'm also setting the minimum MacOS version to 10 just because. Feel free to speak up if you feel the minimum ought to be something else, as long as the desired minimum iOS version isn't below 10.

### Checklist

- [x] Circle CI is passing (code compiles and passes tests).
- [x] There are no breaking changes to public API.
- [x] New test cases have been added where appropriate.
- [x] All new code has been commented with doc blocks `///`.

### CODE REVIEW

**Comment by tanner0101** [comment]
Related to: https://github.com/vapor/vapor/issues/2067

I think we could be a little more conservative with minimum versions. We can always expand support in the future, but we can't reduce it. 

We should also look into `tvOS` / `watchOS`, maybe as a separate issue.

**Comment by twof** [comment]
This actually might not make sense right now given that vapor/vapor can't be deployed to iOS at the moment due to its dependency on OpenSSL. I'll leave it up to you whether to leave this PR open or not. We could still set minimum versions for the other platforms though.

**Comment by tanner0101** [comment]
@twof good point. Maybe we should just do `.macOS(.v10_14)` then? We only currently test Vapor on macOS 10.14 and 10.15, so I think 10.14 as a min req makes sense.

**Comment by MrLotU** [comment]
@tanner0101 We OK to merge this? Or do we need 10_14 for MacOS

**Comment by tanner0101** [comment]
@MrLotU i think just 10_15 and no iOS. We can always widen support in a patch release, but it's not possible to remove any supported versions until Vapor 5.

**Comment by MrLotU** [comment]
I think we should leave iOS in since it's the original reason @twof opened the issue 😄

**Comment by twof** [comment]
@MrLotU We can't deploy to iOS anyway, so I've gone ahead and removed the requirement. See my comment about OpenSSL for why.

**Comment by twof** [comment]
@tanner0101 Given how shakey the Catalina release has been, I could see people staying on 10.14 for longer than expected, so I'd prefer to keep the minimum version at 10.14. Otherwise I'm open to merging this.

**Comment by MrLotU** [comment]
Fixes #2067

**Pull request merged**
