### PR TITLE
Add support for PartialRangeUpTo in validators

### PR DESCRIPTION
**Pull request by adtrevor**
Up until right now, the `.count(...)` and `.range(...)` validators didn't support being passed a `PartialRangeUpTo`. This commit adds support for this.

This also improves and fixes documentation

### CODE REVIEW

**Comment by adtrevor** [comment]
@gwynne Thanks for the review! 🙂 
> Could you add a more-generic overload for accepting any RangeExpression not already covered by the specializations?

I didn't know about this protocol, unfortunately it seems like you can't use a range with `.relative(to:)`: only `Collection`s are accepted (and it uses the collection _indices_ to limit the range! I'll see what a custom collection could do).

**Comment by adtrevor** [comment]
> Unless I missed them (very possible!), there don't seem to be any tests for PartialRangeFrom, can you add a couple?

Done! 🙂

**Comment by gwynne** [comment]
> I didn't know about this protocol, unfortunately it seems like you can't use a range with `.relative(to:)`: only `Collection`s are accepted (and it uses the collection _indices_ to limit the range! I'll see what a custom collection could do).

Nah, don't worry about it - the primary utility of `RangeExpression` is in generically accepting all of the existing range types plus any custom kinds that might be in use. Having thought about it further, I think these APIs are better off staying specific about which types of range they will accept. For example, you theoretically _could_ set it up so you could specify an `UnboundedRange` (the `...` expression) for a `count` or `range` validator, but that's an awful lot of work to make the compiler and runtime do just to validate that yes, the value being checked is indeed a value! 😆

I'm happy with this as it now stands. Ping @tanner0101  to give it a glance before it gets merged.

**Comment by adtrevor** [comment]
@gwynne I saw your comment too late 😃 I can still remove it if that's better without it

**Comment by gwynne** [comment]
@adtrevor I like what you did to implement that! But yeah, I think we're better off without it conceptually as well as for simplicity. Once you revert the commits to add the `RangeExpression` support, I'll merge this. Apologies for sending you down the rabbit hole only to change my mind - I hadn't thought it through at first 😰

**Comment by adtrevor** [comment]
@gwynne No problem! 🙂 Reverted!

**Comment by tanner0101** [comment]
These changes are now available in [4.8.0](https://github.com/vapor/vapor/releases/tag/4.8.0)

**Pull request merged**
