### PR TITLE
Fixes - Restore previous XCTVaporTests behavior if necc.

### PR DESCRIPTION
**Pull request by valeriomazzeo**
Properly restores previous behaviour as described here https://github.com/vapor/vapor/pull/2587#issuecomment-802903118

### CODE REVIEW

**Comment by 0xTim** [comment]
@mxcl does this still satisfy your use case?

**Comment by mxcl** [comment]
Yes, though I wouldn't remove the comment.

**Comment by valeriomazzeo** [comment]
I have re-added the comment

**Review by Joannis — APPROVED** [review]

**Comment by valeriomazzeo** [comment]
Grateful if it would be possible to tag a patch release containing this fix.

**Comment by Joannis** [comment]
Good eye, I forgot that our release bot is broken. I'll do so after the call I'm heading into now.

**Comment by 0xTim** [comment]
This has been released in [4.41.7](https://github.com/vapor/vapor/releases/tag/4.41.7)

**Pull request merged**
