### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by gperdomor**
- Moved to Circle CI 2.0
- Fix MySQLTests
- Removed linux tests from travis build
- Use `xcodebuild` with `xcpretty` instead `swift test`on travis.
- Fix badges and reflect build status for macOS and Linux

### CODE REVIEW

**Comment by gperdomor** [comment]
@tanner0101 Travis checks should be required too, not only circleci :D

**Comment by calebkleveter** [comment]
Why Travis also?

**Comment by gperdomor** [comment]
Travis runs the macOS tests right? or I'm missing something?

**Comment by gperdomor** [comment]
closed in favor #1205

**Comment by tanner0101** [comment]
@gperdomor that PR was just for the vapor beta branch. it's probably worth it to update vapor master branch as well.

**Pull request closed without merging**
