### PR TITLE
Add a way to manually upgrade a request to WebSocket

### PR DESCRIPTION
**Pull request by wacumov**
Adds a way to manually upgrade an incoming request to WebSocket (https://github.com/vapor/vapor/issues/2235).

```swift
app.get("socket") { req in
    // Check things from the request.
    return req.webSocket { req, ws in
        // Handle WebSocket lifecycle here
    }
}
```

### CODE REVIEW

**Comment by flowtoolz** [comment]
@tanner0101 I'd be super excited to see this happen, maybe you know someone who can review it ... 😁

**Comment by 0xTim** [comment]
@wacumov thanks for this and sorry it's languished for so long! If you could fix the conflicts and add a test to show the manual upgrade we can get this merged!

**Comment by wacumov** [comment]
@0xTim I fixed the conflicts and added a test for the manual upgrade.

**Review by 0xTim — APPROVED** [review]
Thanks!

**Pull request merged**
