### PR TITLE
Made error view public

### PR DESCRIPTION
**Pull request by Casperhr**
Had a case where this was needed. And I can see other packages needing this option also

### CODE REVIEW

**Comment by Casperhr** [comment]
We could also consider making the AbortMiddleware.errorResponse public

**Comment by tannernelson** [comment]
I made `ErrorView` not public specifically because it was a bit of a hack. (It's ignoring the view renderer and using `DataFile()`). This should be cleaned up and either conform to `View` or exist as a helper function on ViewRenderer. 

Something like `drop.view.makeError()`.

**Comment by Casperhr** [comment]
Ye that would be a good idea. 

In Laravel you have the abort(int) global

**Comment by LoganWright** [comment]
gonna close this one as well in preference of a public constructor w/ private inner class.

**Pull request closed without merging**
