### PR TITLE
Minor changes to HTTPAccept.swift

### PR DESCRIPTION
**Pull request by timvermeulen**

### CODE REVIEW

**Comment by LoganWright** [comment]
@timvermeulen are you able to resolve the conflicts on this?

**Comment by timvermeulen** [comment]
@LoganWright Not really 😕 It compiles on my Mac just fine, but CircleCI says `error: The dependency graph could not be satisfied`. I'm not sure what causes it.

**Comment by tannernelson** [comment]
@timvermeulen clean your project and build it again to re-fetch the dependencies.

**Comment by timvermeulen** [comment]
@tannernelson It's not my project that is failing to build, it's the integrated tester.

**Comment by LoganWright** [comment]
@timvermeulen @tannernelson why is it pulling qutheory domains? Anyone have ideas on this, is there another dependency misnamed somewhere?

**Comment by LoganWright** [comment]
@timvermeulen I pulled these commits into our repo as #663 so we can work off it from there. Do you have write access?

**Pull request closed without merging**
