### PR TITLE
Ensure .env is loaded before configuring application

### LINKED ISSUE #2090: Variables defined in .env file are not available during configuration
The environment variables are not available through `Environment.get()` during the app configuration phase; where they'd be most used.

### Steps to reproduce

1. Create a new app using the api-template.
2. Reference a variable using `Environment.get()` somewhere in the body of `configure(_ app: Application)`.
3. Run the app from the CLI using `vapor build && vapor run`

### Expected behavior 

- The value of the variable is available.

### Actual behavior

- The `Environment.get()` returns `nil`.

PS: The same variable can be accessed later on, for instance as a response to a request. 

### Environment

* Vapor Framework version: 4.0.0-beta.1
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.15 and Ubuntu 18.04

### Additional Info

* A sample project is attached.
[sample.zip](https://github.com/vapor/vapor/files/3795805/sample.zip)

### PR DESCRIPTION
**Pull request by jimmya**
Fixes #2090

I encountered that `DirectoryConfiguration` isn't working properly when using Xcode. I reverted the changes to the Vapor 3 implementation as they seem to work fine.

Furthermore I noticed that the .env file is loaded without prefixing the current working directory. Leading to a path that is ambiguous to the project. 

I also exposed the `loadDotEnv` file function and called it before configuring the app. The reason I did is because it's non blocking it requires the `.wait()` addition. Causing the function to throws. As I didn't want to break any api and I see the loading of the .env file as something that is opt-in and not for everyone applicable.

### Checklist

- [x] Circle CI is passing (code compiles and passes tests).
- [x] There are no breaking changes to public API.
- [x] New test cases have been added where appropriate.
- [x] All new code has been commented with doc blocks `///`.

### CODE REVIEW

**Comment by MrLotU** [comment]
@jimmya Thanks for the PR. 2 questions:
1. Could you resolve the merge conflicts?
2. Could you remove the `DirectoryConfig` part of the PR? I have not heard issues about this before so it might be something setup related. However it should not block us from merging the `.env` fix.

Thanks!

**Comment by jimmya** [comment]
@MrLotU I've resolved the conflicts. 
I'm interested to know how to get the directory config working when building from Xcode.
When reverting the changes in `DirectoryConfiguration.swift` I get the following warning in console when loading the `.env` file.

`warning: No custom working directory set for this scheme, using /Users/jimmy/Library/Developer/Xcode/DerivedData/vapor-blxggugtabajjlfsjnivdaqvblnk/Build/Products/Debug`

Is there some additional configuration needed when running the project in Xcode as the docs don't show this.

**Comment by MrLotU** [comment]
With Xcode 11 you need to go into your scheme options and set a custom root for your project. See https://github.com/vapor/core/releases/tag/3.9.2

**Comment by jimmya** [comment]
@MrLotU Ahhh I missed that one! Thanks. I reverted the change and added a note to the documentation pointing other in the right direction :)

**Comment by MrLotU** [comment]
Closing per https://github.com/vapor/vapor/pull/2125

**Pull request closed without merging**
