### PR TITLE
Cors

### PR DESCRIPTION
**Pull request by LoganWright**
Closing #731

### CODE REVIEW

**Comment by skreutzberger** [comment]
Does the pull request contain tests or an example? I am currently trying to compare it with my own old [CORS implementation](https://github.com/SwiftyBeaver/SBWebsite/blob/master/Sources/SBWebsite/Middleware/CorsMiddleware.swift) (which also has no tests but was never meant to be part of Vapor) but I do not immediately which one I should take now.

@LoganWright Maybe we can push a bit the need for tests, examples and a page or section in the documentation about a feature or change with each pull request? In that way contributors get used to not just only contribute code but also docs or examples which would help the general userbase.

**Comment by nickskull** [comment]
@skreutzberger No, I've started writing tests yesterday, so they're not yet ready, but my plan is to have it done today or tomorrow.

As for example, I think the easiest will be to update the docs with section on how to add CORS support.

@LoganWright Please don't merge before I finish the tests 😇

**Comment by nickskull** [comment]
I've added some very basic tests, have a look when you have time :)

**Comment by nickskull** [comment]
@LoganWright I am not entirely sure what is going on with codecov. Am I missing any docs anywhere or is it codecov just being annoying? :)  Otherwise this PR should be ready for review.

I'm going to be making a PR to the docs with the changes soon so that people know how to use this :)

**Comment by LoganWright** [comment]
@nickskull the code cov stuff is in the first comment, they just update the same comment each time, and factor in the change in code cov %. Updated to master so travis can run again, then let's merge this.

**Pull request merged**
