### PR TITLE
Provide a reason when route cannot be found.

### PR DESCRIPTION
**Pull request by maciejtrybilo**
Currently when the router cannot find an endpoint for a requested resource the reason in the response is "Not Found". This PR makes the reason more specific which allows the 404 to be easier do diagnose.

### Checklist

- [ ] Circle CI is passing (code compiles and passes tests).
- [ ] There are no breaking changes to public API.
- [ ] New test cases have been added where appropriate.
- [ ] All new code has been commented with doc blocks `///`.

### CODE REVIEW

**Comment by 0xTim** [comment]
+1 on this, might be less noisy to just print the path rather than the whole string in the reason though - open to suggestions

**Comment by maciejtrybilo** [comment]
Thanks @0xTim. I don't mind either way. I'm happy to change if the reviewer prefers. 

BTW, any idea why circle ci is stuck on one of the tests? It's been pending for days...

**Comment by 0xTim** [comment]
@maciejtrybilo at a guess it's waiting for a review approval to be kicked off

**Comment by calebkleveter** [comment]
The compatibility suite needs to be run manually.

**Comment by maciejtrybilo** [comment]
@0xTim Updated to only print the path.

**Comment by 0xTim** [comment]
@tanner0101 its to bring parity with Vapor 2 and for logs as well. Especially in a browser there are lots of 404s that confuse people (mainly favicons and Apple touch icons) so it would be good to surface those with the 404s.

**Comment by maciejtrybilo** [comment]
@0xTim Thanks! Do you have the credentials to rerun the failed test? It looks like it timed out.

**Comment by 0xTim** [comment]
@maciejtrybilo I do not unfortunately (although I think I should do @tanner0101 ?)

Anyway, I don't think rerunning would help, it looks like the error is a package dependency issue with that package in the compatability suite, though it was last run a while ago so might work now.

**Comment by 0xTim** [comment]
@tanner0101 bump

**Comment by kylebrowning** [comment]
This is much more useful for logs than it is the browser. 

Hosting on AWS you just see abort 404 in cloud watch so you get nothing.

**Comment by MrLotU** [comment]
IIRC by adding it to `Abort` it'll both appear in logs & in the HTTP response, correct?

**Comment by tanner0101** [comment]
I still don't fully understand the benefit behind this. In the browser, the console shows the request for a given error which includes the path.

**Comment by kylebrowning** [comment]
@tanner0101 I can provide some context here.

on AWS, this is all you get to see when there is a 404.

Screen Shot 2020-01-23 at 6 18 46 PM


I wrote my own middleware to solve this, but it would be nice to have OOB

**Comment by tanner0101** [comment]
@kylebrowning ah okay, that context helps a lot. I agree that could be improved. That should be fixed by improving ErrorMiddleware which has access to the incoming request and can get the path that way.

**Comment by kylebrowning** [comment]
@tanner0101 I age with that approach, that's why I copied ErrorMiddleware and just modified it.

**Comment by 0xTim** [comment]
@tanner0101 do you have permissions to kick the CI or shall I just merge it?

**Comment by MrLotU** [comment]
I'll see if I can give the CI a kick

**Comment by 0xTim** [comment]
@maciejtrybilo do you want to do the update?

**Comment by maciejtrybilo** [comment]
@0xTim Yep, I should have some time soon.

**Comment by maciejtrybilo** [comment]
Closing and opening a new PR instead: https://github.com/vapor/vapor/pull/2170

**Pull request closed without merging**
