### PR TITLE
make mediaTypes public (Sources/Vapor/Content/MediaType.swift)

### PR DESCRIPTION
**Pull request by truemetal**
issue #933

### CODE REVIEW

**Comment by tanner0101** [comment]
I'd prefer to expose these as a static variable on HTTP requests and responses.

```swift
import HTTP
extension Message {
    public var mediaTypes: [String: String] {
        get { return mediaTypes }
        set { mediaTypes = newValue }
    }
}
```

This would give better discoverability.

**Comment by truemetal** [comment]
@tanner0101 not sure I follow your idea on putting it under `Message` (especially, why there's a `set`); but I've just committed a change that moves that dict under `MediaType` struct.

**Comment by tanner0101** [comment]
@truemetal putting it on message would allow us to do like

```swift
Request.mediaType["js"] // application/js
// and
Response.mediaType["html"] // application/html
```

**Comment by truemetal** [comment]
@tanner0101 ok, np, moved that under Message 
`MediaType` struct goes away

**Comment by truemetal** [comment]
@tanner0101 do you anticipate media types being used often by it's shorthand counterpart? If so maybe this would be a nice feature

```
private let mediaTypes = [
    "js" : "application/js",
    "html" : "application/html"
]

public enum MediaType : String {
    case js,
    html

    func mediaTypeValue() -> String {
        return mediaTypes[self.rawValue]!
    }
}

MediaType.js.mediaTypeValue() // application/js
MediaType.html.mediaTypeValue() // application/html

MediaType(rawValue: "html")?.mediaTypeValue() // application/html
```

**Comment by tanner0101** [comment]
conveniences for accessing media types (like we have with `HeaderKey` https://github.com/vapor/engine/blob/b47548807ccfff6a6ca073888e4bfce2cbf3d8c0/Sources/HTTP/Models/Headers/Headers.swift#L45) would be awesome

**Comment by truemetal** [comment]
@tanner0101 it suffers from similar to this build error: https://travis-ci.org/vapor/vapor/jobs/218877073

Another thing I've noticed - I've made PR from my `master`, didn't make `feature` for it 
Also now I see maybe it's better to base this PR from `1` branch rather then from `master`?

**Pull request merged**
