### PR TITLE
Run Vapor in a non-blocking main thread (Issue #1268)

### PR DESCRIPTION
**Pull request by khoogheem**

### CODE REVIEW

**Comment by Joannis** [comment]
Ironically, this failed on macOS. I see you're re-running it though :)

**Comment by Joannis** [comment]
Seems to be a Redis issue

**Comment by tanner0101** [comment]
any idea why this change is causing redis to fail?

**Comment by Joannis** [comment]
It probably isn't causing redis to fail. It's happened more often in PRs from a week ago.

**Comment by khoogheem** [comment]
If I recall correctly from what I looked at for the Redis test.  There is nothing in this change that should have been touched by the test.  So I am pretty confident that the non-blocking change and the Redis failure are two different issues.

**Comment by Joannis** [comment]
I re-ran the tests, this works 👍

**Comment by tanner0101** [comment]
cool, thanks @khoogheem !

**Pull request merged**
