### PR TITLE
Remove HeadResponder

### LINKED ISSUE #2680: HEAD route ignores Middlewares
### Describe the bug

DefaultResponder will create a HEAD route for any constant-path GET route by default. But this behaviour prohibits developers from inserting middleware to GET route without differentiating the behaviour of GET and HEAD.

```swift
// If the route isn't explicitly a HEAD route,
// and it's made up solely of .constant components,
// register a HEAD route with the same path
if route.method == .GET &&
route.path.allSatisfy({ component in
    if case .constant(_) = component { return true }
    return false
}) {
    let headRoute = Route(
        method: .HEAD,
        path: cached.route.path,
        responder: middleware.makeResponder(chainingTo: HeadResponder()),
        requestType: cached.route.requestType,
        responseType: cached.route.responseType)
    
    let headCachedRoute = CachedRoute(route: headRoute, responder: middleware.makeResponder(chainingTo: HeadResponder()))
    
    router.register(headCachedRoute, at: [.constant(HTTPMethod.HEAD.string)] + path)
}
```

### To Reproduce

1. Create a GET route with a Middleware group that inserts additional headers.

```swift
public struct RandomHeaderMiddleware: Middleware {
    public func respond(to request: Request, chainingTo next: Responder) -> EventLoopFuture<Response> {
        next.respond(to: request).map {
            response.headers.add(name: "x-random", value: "\(Int.random(in: 0...100))")
            return response
        }
    }
}
```

```swift
routes.grouped(RandomHeaderMiddleware()).get {
    return "Hello World!"
}
```

2. When a HEAD request is sent to the endpoint, ```x-random``` header will not exist. By contrast, when a GET request is sent, it will exist on the response.

### Expected behavior

1. Middleware will be accessible to HEAD method as well.
2. HEAD and GET methods will respond with same headers.

### Environment

* Vapor Framework version: 4.48.3
* Vapor Toolbox version: 18.3.3
* OS version: macOS Big Sur 11.5.2

### Additional context

If the fix I suggested is not feasible, I think at least there should be an option to not auto-generate HEAD route when the developer needs. Currently, there isn't one without making dynamic path with wildcards or parameters.

I could just override the HEAD route, but it feels like an undefined behaviour that needs to be amended.

### PR DESCRIPTION
**Pull request by baarde**
The HEAD method is identical to GET except that the server must not send content in the response ([RFC 9110, section 9.3.2](https://datatracker.ietf.org/doc/html/rfc9110#HEAD)).

The previous default behaviour of returning 200 OK to every HEAD request to a constant route is not standard-compliant.

The new behaviour is to always forward the request to the GET route, unless the developer explicitely configured a custom HEAD route.

This PR fixes #2680 and #2749.

### CODE REVIEW

**Review by gwynne — APPROVED** [review]
LGTM, @0xTim?

**Review by 0xTim — CHANGES_REQUESTED** [review]
Sorry for the delay in this. I think this is good, but I'd like to see a test for the explicit override of a HEAD request

**Comment by baarde** [comment]
@0xTim I think this is already covered by ~~`testExplicitHeadRouteOverridesGeneratedHandler`~~ `testExplicitHeadRouteOverridesForwardingToGet` (I've renamed the method to reflect the implementation change).

**Review by 0xTim — APPROVED** [review]
Ah I missed that. Ok this looks fine to me

@owainhunt since you did the original PR, does the overriding as described work for you?

**Comment by owainhunt** [comment]
LGTM 👍

**Pull request merged**
