### PR TITLE
Feature/error with code

### PR DESCRIPTION
**Pull request by Casperhr**
Added a new type of custom Error with a code
And error response now always have a code field

### CODE REVIEW

**Comment by tannernelson** [comment]
This change would require Vapor 2.0 since it adds an enum case. 

I think a better way to solve this and keep Vapor at 1.x would be something like:

```swift
protocol AbortError: Error {
    var message: String
    var code: Int
    var status: Status
}
```

```swift
extension Abort: AbortError {
    ...
}
```

This way Abort continues to work normally (we can deprecate it). And users can conform their own objects to AbortError.

**Comment by Casperhr** [comment]
@tannernelson Agree, good idea!

**Comment by Casperhr** [comment]
Consider having few extra fields @tannernelson 

-shouldReport: Bool
-meta: Node

**Comment by LoganWright** [comment]
Closing for now we can implement protocol in separate PR.

**Pull request closed without merging**
