### PR TITLE
Rename makeResponse to response

### LINKED ISSUE #1671: Deprecate makeResponse() in favour of response()
I believe that `req.makeResponse()` should be deprecated, in favour of `req.response()`.

* The latter reads much nicer: e.g `return req.response()` instead of `return req.makeResponse()`.

This would be introduced in Vapor 3.1, and `makeResponse` would be marked as deprecated.

### PR DESCRIPTION
**Pull request by jamiebishop**
This PR closes #1671, and renames `req.makeResponse()` to `req.response()`. 

### Checklist

- [x] Circle CI is passing (code compiles and passes tests).
- [x] There are no breaking changes to public API.
- [x] New test cases have been added where appropriate.
- [x] All new code has been commented with doc blocks `///`.

### CODE REVIEW

**Comment by tanner0101** [comment]
I'm going to merge this through so we can get a 3.1 branch started. If anyone has comments about this change, let's discuss on the 3.1 branch.

**Comment by penny-coin** [comment]
Hey @jamiebishop, you just merged a pull request, have a coin! 

You now have 2 coins.

**Comment by 0xTim** [comment]
I’m assuming this would require either a deprecation or be held until Vapor 4 since it contains a breaking change?

**Comment by jamiebishop** [comment]
:+1:

**Pull request merged**
