### PR TITLE
Add support for overwriting slugName in resource

### PR DESCRIPTION
**Pull request by kdawgwilk**
This is related to the issue #691 and the solution I came up with with a little experimentation.  I don't see this as the final draft or the best solution but figured a PR would be the best place to get some feedback so others could benefit.

### CODE REVIEW

**Comment by kdawgwilk** [comment]
I really want to use an unlabeled parameter for the slugName but generics are struggling to resolve correctly when I try.  Also I think I am missing the default on the bottom resource function.

**Comment by kdawgwilk** [comment]
Or maybe its better to just use the resource name and attach a `_id` to the end of it so it doesn't end up ambiguous?

**Comment by LoganWright** [comment]
@kdawgwilk I think this is a good start, we'd also need to go into generated code so that the generated slug names there also don't interfere w/ here.

I'm trying to think of some type of alternate system, but don't have one immediately.

**Comment by LoganWright** [comment]
@kdawgwilk sorry this got stale, I'm updating now, I think this is safe to merge.

@tannernelson can you take a quick look regarding whether this would interfere w/ generated code? I believe I was mistaken thinking it would, but would like your second look.

**Pull request merged**
