### PR TITLE
remove unused imports

### PR DESCRIPTION
**Pull request by jpsim**
For fun, I wrote a tool to check for unused imports in Swift files and tested it on Vapor. Here's what it found 😄

### CODE REVIEW

**Comment by jpsim** [comment]
I found unused imports in Vapor's external dependencies too, if anyone wants to make PRs for those, feel free:

* `Console/Command.swift`: Polymorphic
* `HMAC/Method.swift`: Core Essentials
* `HTTP/Client+Foundation.swift`: URI
* `HTTP/Response+Foundation.swift`: URI
* `JSON/JSON.swift`: Core
* `URI/URI+Modification.swift`: Core

**Comment by hhanesand** [comment]
@jpsim Could you link us to the tool you used? I'm very interested in using it!

**Comment by LoganWright** [comment]
@jpsim awesome, definitely share the tool with us and excited to clean up some of those! Is this part of SwiftLint?

**Comment by jpsim** [comment]
The "tool" is just a hacked together ~50 line script that imports SourceKittenFramework right now. It's quite slow too, taking about 10 minutes to run on vapor. I'll be publishing something once I can improve its performance and package it up in something easier to use.

**Pull request merged**
