### PR TITLE
add DotEnvFile type for loading .env (dotenv) files

### LINKED ISSUE #1885: add .env (dotenv) support
It should be possible to load Environment variables into an Vapor app from a .env file. Examples of this can be seen in various other frameworks (Laravel, NodeJS etc.)

Some examples of what should be allowed:

```
FOO="Foo Bar"
FOO2='Foo Bar'
FOO3=Bar
```

### PR DESCRIPTION
**Pull request by tanner0101**
- Adds a new `DotEnvFile` type that can read and load `.env` (dotenv) files.
- Adds logic to load `.env` file from current working directory on app boot.
- `DotEnvFile.Parser` uses `ByteBuffer` with minimal string operations. 
- Fixes #1885. 

### Data structure

```swift
public struct DotEnvFile {
    public struct Line {
        public let key: String
        public let value: String
    }

    public let lines: [Line]
}
```

### Usage

```swift
let fileio: NonBlockingFileIO
let elg: EventLoopGroup
let file = try DotEnvFile.read(path: ".env", fileio: fileio, on: elg.next()).wait()
for line in file.lines {
    print("\(line.key)=\(line.value)")
}
file.load(overwrite: true) // loads all lines into the process
```

### Edge-case support

Here is the test file used ([source](https://github.com/motdotla/dotenv/blob/master/tests/.env)):

```env
NODE_ENV=development
BASIC=basic

# previous line intentionally left blank
AFTER_LINE=after_line
UNDEFINED_EXPAND=$TOTALLY_UNDEFINED_ENV_KEY
EMPTY=
SINGLE_QUOTES='single_quotes'
DOUBLE_QUOTES="double_quotes"
EXPAND_NEWLINES="expand\nnewlines"
DONT_EXPAND_NEWLINES_1=dontexpand\nnewlines
DONT_EXPAND_NEWLINES_2='dontexpand\nnewlines'
# COMMENTS=work
EQUAL_SIGNS=equals==
RETAIN_INNER_QUOTES={"foo": "bar"}
RETAIN_INNER_QUOTES_AS_STRING='{"foo": "bar"}'
INCLUDE_SPACE=some spaced out string
USERNAME="therealnerdybeast@example.tld"
```

### Todo

- [ ] Backport to Vapor 3
- [x] Add doc blocks

### CODE REVIEW

**Comment by MrLotU** [comment]
Since this is automatically done, can we load it into the the `Application`s `Environment` or something?

**Comment by vzsg** [comment]
Is there any benefit to doing this much ceremony with NonBlockingFileIO if the code is only going to read the complete file once on boot?

**Comment by tanner0101** [comment]
> Since this is automatically done, can we load it into the the `Application`s `Environment` or something?

That's what `DotEnvFile.load()` does. I've added an example of this in the usage section. 

> Is there any benefit to doing this much ceremony with NonBlockingFileIO if the code is only going to read the complete file once on boot?

Application already needs to have a `NonBlockingFileIO` here to power the `FileIO` used by `FileMiddleware`, `req.streamFile`, etc. More generally though, I'm preparing for Foundation on Windows to go through a phase (like with Linux) where it's mostly unimplemented for a year or two. So if any new code can reasonably avoid using Foundation's APIs, I think that would be a good idea.

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 1071 coins.

**Pull request merged**
