### PR TITLE
Controllers to use RESTFul verbs

### PR DESCRIPTION
**Pull request by wess**
Just changed the controller's default mapped methods to be that of RESTFul verbs. This will make it clearer for developers to know what type of request they are making.

### CODE REVIEW

**Comment by LoganWright** [comment]
@qutheory/contributors How do people feel about this semantic change? It diverges from concepts established in frameworks like Rails, however, semantically, it's a bit more clear what's getting called. 

This makes things much closer to route groups, perhaps we could use a variant of route group to provide this behavior more efficiently.

**Comment by jchannon** [comment]
As it should be! Also where is OPTIONS!?

**Comment by LoganWright** [comment]
@jchannon the goal is to provide `options` by default somehow based on what methods are implemented

**Comment by Casperhr** [comment]
On more advanced apis you will have several POST/PATCH/GET on same model. Fx patch for update is fine, but if you can pass files as multipart entity, it has to be POST

Therefor I vote for not naming the function the method by default

**Comment by jchannon** [comment]
Not really sure what Casper is saying, I don't know vapor too well but a
controller should be able to handle multiple verbs

**Comment by Casperhr** [comment]
That was my point, I don't like a pattern where you think the http method is equal the function name

**Comment by wess** [comment]
Well if you look at other rest api frameworks, you will see this pattern for class based namespacing, if you want to do custom/multiple put, you still could and just route them. @Casperhr argument is fine, but the way it currently is, are you not still forcing them to your pattern/naming of functions?

**Comment by kdawgwilk** [comment]
I am 👍 for this change because this was one of the first things that stuck out to me as being odd when I first created a controller

**Comment by wess** [comment]
I need to fix the CI

**Comment by tannernelson** [comment]
This should be included now.

**Pull request closed without merging**
