### PR TITLE
Better Cookie Parsing (#2504)

### LINKED ISSUE #2504: Fails to parse cookie if it has % in its name
Vapor cannot parse the cookies that has `%` in its name.
(Similar issue: #2359)

According to RFC6265  `cookie-name = <token, defined in [RFC2616], Section 2.2>`.
And accodging to RFC2616:

```
token          = 1*<any CHAR except CTLs or separators>
CHAR           = <any US-ASCII character (octets 0 - 127)>
CTL            = <any US-ASCII control character
                        (octets 0 - 31) and DEL (127)>
separators     = "(" | ")" | "<" | ">" | "@"
                | "," | ";" | ":" | "\" | <">
                | "/" | "[" | "]" | "?" | "="
                | "{" | "}" | SP | HT
```

If I understand correctly, `%` is valid.

`firstParameterToken` tries to find `=` to separate cookie name and value.
But it fails when it find character that is `!character.isDirectiveKey`.
https://github.com/vapor/vapor/blob/45d19c3d9b73f15d18ca51077e165a8fc1ef2f54/Sources/Vapor/HTTP/Headers/HTTPHeaders%2BDirective.swift#L133-L143

And `%` is not `isDirectiveKey`.
https://github.com/vapor/vapor/blob/45d19c3d9b73f15d18ca51077e165a8fc1ef2f54/Sources/Vapor/HTTP/Headers/HTTPHeaders%2BDirective.swift#L249-L251

### Steps to reproduce

Open developer tool and create new cookie that has `%` in its name.
You'll find `request.cookies.all` is empty.

### My problem

My site is `mysite.example.com` and `example.com` is not under my control.
When user access to `example.com`, it sets the cookie `some%40key=value` and `Domain=.example.com` (`%40` is url encoded `@`).
This cookie also affects my site.

`HTTPCookies.init` returns `nil` if there's invalid directive.
https://github.com/vapor/vapor/blob/45d19c3d9b73f15d18ca51077e165a8fc1ef2f54/Sources/Vapor/HTTP/Headers/HTTPCookies.swift#L241-L249
So `%` cookie breaks all other cookies.
(I think this initializer should just ignore invalid directives)

### PR DESCRIPTION
**Pull request by gregoryyoung2**
Improves cookie parsing (#2511) 

- Directive keys (i.e. cookie names) can now include `%` characters (fixes #2504) 
- If a directive has no value (i.e. from failing to parse properly) it will be excluded from `HTTPCookies`
- If some directives have values and others do not, the directives with values will still be included in `HTTPCookies`

### CODE REVIEW

**Review by gwynne — CHANGES_REQUESTED** [review]
Please add unit tests for the new behavior.

**Comment by gregoryyoung2** [comment]
> Please add unit tests for the new behavior.

done in cc2218e

**Comment by Joannis** [comment]
Before gwynne gets to it, our release process uses the PR body as release notes.
https://github.com/vapor/vapor/blob/master/.github/contributing.md#releases

**Comment by gregoryyoung2** [comment]
Quoting old PR body in the discussion:

> #2504 brings up an issue where it is valid for a cookie name to include a `%` character, however Vapor fails to consider this as a valid directive key. This is an issue Vapor developers may run into when sharing a parent domain with other applications. 
> 
> Additionally, if any cookies fail to parse (due to having a `%` in the name, for example), this will result in an empty cookie jar. We should only exclude the cookies which fail to parse, and include the ones which parse correctly.
> 
> I first extended the expression in `Character.isDirectiveKey` to return true if `self == Character("%")`. I then adjusted the `HTTPCookies` initializer to only include directives that have both a key and value, rather than return `nil` if any directive is missing a value.
> 
> If it is important to keep the API for this `HTTPCookies.init` stable, we can leave it as an optional initializer (I will update the PR).

**Comment by t-ae** [comment]
Nice patch!

The implementation does not conform to RFC yet.
As I wrote in #2504, there are some more characters that should be allowed.

```
!"#$%&'*+^`
```

It'll be great if all of them are allowed (I'm not 100% sure if all of them should be allowed, though).

By the way I think the name `isDirectiveKey` is not good.
What it check is if the character is allowed in `token`. `token` is a term in RFC, so renaming it to `isTokenCharacter` and providing the link to RFC will make it clearer.

**Comment by gregoryyoung2** [comment]
> Nice patch!
> 
> The implementation does not conform to RFC yet.
> As I wrote in #2504, there are some more characters that should be allowed.
> 
> ```
> !"#$%&'*+^`
> ```
> 
> It'll be great if all of them are allowed (I'm not 100% sure if all of them should be allowed, though).
> 
> By the way I think the name `isDirectiveKey` is not good.
> What it check is if the character is allowed in `token`. `token` is a term in RFC, so renaming it to `isTokenCharacter` and providing the link to RFC will make it clearer.

I agree with all of these points, but due to the lack of documentation for this area of the project I wanted to make this change as small as possible to avoid unintended fallout from the change. Someone who has a more comprehensive understanding of the project might be able to achieve full RFC conformance, but this is sufficient for now.

**Comment by 0xTim** [comment]
@gwynne ping - you happy with these changes?

**Review by gwynne — APPROVED** [review]
I'm not really 100% satisfied with silently dropping cookies that won't parse, but it's the best solution available without further work to improve RFC compliance and provide "permissive" parsing as a configurable option, which can be done in a future PR.

**Comment by tanner0101** [comment]
These changes are now available in [4.36.1](https://github.com/vapor/vapor/releases/tag/4.36.1)

**Pull request merged**
