### PR TITLE
add new backers

### PR DESCRIPTION
**Pull request by tanner0101**

### CODE REVIEW

**Comment by tanner0101** [comment]
@ScottRobbins @ksmandersen thanks for becoming a backer! Let me know if the picture / link used here is good. Also please DM me at http://vapor.team or tanner@vapor.codes with your physical address for your tier rewards.

**Comment by grundoon** [comment]
Wow, just noticed that the fees through Open Collective for monthly small amounts are ludicrous – e.g. "18.00% payment processor fee" on mine.

Would it help if I/we switched to annual or something?

**Comment by tanner0101** [comment]
@grundoon GitHub's sponsorship program has zero fees and is also matching contributions for the first year. So, if it's possible to switch to GitHub, that makes your contribution go a lot further! 

One catch is that if you pay for other GitHub things yearly then you must also pay the sponsorship yearly. 

> Our billing system currently only supports a single billing cycle per account. If you pay for GitHub or a marketplace listing on a yearly basis then everything must be done according to that billing cycle. We recognize this is not ideal! We'd like to change this but it's not a simple fix, so it is not a high priority at the moment.

**Comment by grundoon** [comment]
I would have found that a LOT faster if either the Sponsor badge at the top linked directly to the GH Sponsorship (instead of only the external OC option), or there were the expected "Sponsor" button in addition to "Follow" on your personal profile. Just sayin'. :)

**Comment by ScottRobbins** [comment]
@tanner0101 Yep, picture and link are good.

**Pull request merged**
