### PR TITLE
Fixed typo satisifed -> satisfied

### PR DESCRIPTION
**Pull request by BenedictSt**
Sources/Vapor/Environment/Environment.swift

satisifed -> satisfied

### CODE REVIEW

**Comment by BenedictSt** [comment]
I also found a few more typos. Should I create a big pull request for all or one for every typo?

**Comment by 0xTim** [comment]
@BenedictSt One PR would be great thanks!

**Review by strelnikov — APPROVED** [review]

**Comment by 0xTim** [comment]
@BenedictSt did you want to add any more typos to this PR?

**Comment by BenedictSt** [comment]
@0xTim Sorry for the late response. I had a lot going on recently.

**Review by 0xTim — APPROVED** [review]
Great thanks!

**Pull request merged**
