### PR TITLE
Created ParamatersContainer.advance(_:) method

### PR DESCRIPTION
**Pull request by calebkleveter**
This method takes in a an  value, which is the number of values from remove from the beginning of the  array

### Checklist

- [x] Circle CI is passing (code compiles and passes tests).
- [x] There are no breaking changes to public API.
- [x] New test cases have been added where appropriate.
- [x] All new code has been commented with doc blocks `///`.

### CODE REVIEW

**Comment by calebkleveter** [comment]
I guess I got feature happy 😄. Not really sure if this would do any good, so maybe we should close this PR. Go ahead if you think that's best.

P.S. Something that just crossed my mind. What if `ParamatersContainer` conformed to `Sequence`?

**Comment by tanner0101** [comment]
@calebkleveter np, if there's something that's not possible to do without this patch, I'm happy to merge it. But otherwise, I prefer to merge PRs that delete code instead of adding it :)

As for conforming to Sequence, that is interesting. I think it could be difficult without exposing internal types since you usually pull out different Types for each item in the sequence.

**Comment by calebkleveter** [comment]
So right now, the public `values` property on the `Parameters Container` class is get-only, and this just it partially mutable.

**Comment by MrLotU** [comment]
Since Vapor 4 will change the way Parameters are handled and there's no direct purpose for this. I feel like we should close this PR to clean up.
CC: @calebkleveter

**Comment by tanner0101** [comment]
Yup, https://forums.swift.org/t/named-routing-parameters/19434 was partially inspired by this PR. It should fix this problem and others with one change.

**Comment by MrLotU** [comment]
@calebkleveter I closed the PR, but leaving the branch around for now, maybe copy it to a fork if you want to keep the code so we can clean up? :)

**Comment by calebkleveter** [comment]
Deleted 😄I don't have any need for it.

**Comment by MrLotU** [comment]
👍

**Pull request closed without merging**
